core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('lets-get-started', views.initialise_members, name='create_profile'),
    path('profile', views.update_primary_member, name='profile'),
    path('members', views.list_members, name='list_members'),
    path('members/add', views.AddMember.as_view(), name='add_member'),
    path('members/<int:pk>/update',
         views.update_member, name='update_member'),
    path('members/<int:pk>/delete',
         views.DeleteMember.as_view(), name='delete_member')
]

mealplanner/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('core/', include('core.urls')),
    path('user/', include('accounts.urls')),
    path('', include('meals.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

meals/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.list_meals, name='meal_list'),
    path('meals/', views.meal_manager, name='meal_manager'),
    path('meal/<int:pk>/update', views.UpdateMeal.as_view(), name='update_meal'),
    path('meal/<int:pk>/delete', views.delete_meal, name='delete_meal'),
    path('meal/<str:date>', views.meal_detail, name='meal_detail')
]

meals/models.py
from django.db import models
from core.models import Member
from accounts.models import User


class Ingredient(models.Model):
    name = models.CharField(max_length=100)


class Meal(models.Model):
    name = models.CharField(max_length=255)
    date = models.DateField()
    members = models.ManyToManyField(Member)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    mealtime = models.CharField(max_length=255, null=True, blank=True)
    ingredients = models.ManyToManyField(Ingredient)

    def __str__(self):
        return '%s' % self.name

meals/forms.py
from django import forms
from .models import Meal
from core.models import Member

MEALTIME_CHOICES = [
    ('Breakfast', 'Breakfast'),
    ('Lunch', 'Lunch'),
    ('Dinner', 'Dinner'),
]


class CustomModelMultipleChoiceField(forms.ModelMultipleChoiceField):
    def label_from_instance(self, member):
        return "%s" % member.name


class CreateMealForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        """ Grants access to the request object so that only members of the current user
        are given as options"""

        self.request = kwargs.pop('request')
        super(CreateMealForm, self).__init__(*args, **kwargs)
        self.fields['members'].queryset = Member.objects.filter(
            user=self.request.user)

    class Meta:
        model = Meal
        fields = ['name', 'mealtime', 'date', 'members']

    name = forms.CharField()
    date = forms.DateInput()
    mealtime = forms.ChoiceField(choices=MEALTIME_CHOICES)
    members = CustomModelMultipleChoiceField(
        queryset=None,
        widget=forms.CheckboxSelectMultiple
    )

meals/views.py
import json
from datetime import datetime
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.views.generic import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Meal
from core.models import Member
from .forms import CreateMealForm
from django.contrib.auth.decorators import login_required
from datetime import datetime


@login_required
def list_meals(request):
    members = Member.objects.filter(user=request.user)

    meals_queryset = []
    default_mealtime = 'Dinner'
    active_date = datetime.today().strftime('%Y-%m-%d')
    active_page = 0
    active_index = 0

    if request.method == 'POST':
        form = CreateMealForm(request.POST, request=request)

        if form.is_valid():
            meal = Meal(
                name=request.POST['name'],
                date=request.POST['date'],
                mealtime=request.POST['mealtime'],
                user=request.user
            )
            meal.save()

            member_ids = form.cleaned_data['members'].values_list(
                'id', flat=True)

            for id in member_ids:
                meal.members.add(id)

            default_mealtime = meal.mealtime
            active_date = meal.date
            active_page = request.POST['page']
            active_index = request.POST['activeIndex']

    else:
        form = CreateMealForm(request=request)
        form.request.path = '/add/'

    queryset = Meal.objects.filter(user=request.user).order_by(
        'date').prefetch_related('members')

    meals = []
    for meal in queryset:
        meal_members = [member.name for member in meal.members.all()]
        meals.append({
            'id': meal.id,
            'name': meal.name,
            'date': meal.date.isoformat(),
            'mealtime': meal.mealtime,
            'members': meal_members
        })

    context = {}
    context['meals'] = json.dumps(meals)
    context['form'] = form
    context['default_mealtime'] = default_mealtime
    context['active_date'] = active_date
    context['active_page'] = active_page
    context['active_index'] = active_index
    context['members'] = members
    context['member_names'] = json.dumps(
        list(members.values_list('name', flat=True)))

    return render(request, 'meals/list_meals.html', context)


def meal_detail(request, date):
    return HttpResponse('Hey')


def delete_meal(request, pk):
    meal = Meal.objects.get(pk=pk)
    meal.delete()
    return JsonResponse({'status': 200})


@login_required
def meal_manager(request):

    all_meals_queryset = Meal.objects.filter(
        user=request.user).distinct('name')

    all_meals = []
    for meal in all_meals_queryset:
        meal_ingredients = [
            ingredient.name for ingredient in meal.ingredients.all()]
        all_meals.append({
            'id': meal.id,
            'name': meal.name,
            'date': meal.date.isoformat(),
            'mealtime': meal.mealtime,
            'ingredients': meal_ingredients,
        })

    context = {
        'meals': json.dumps(all_meals)
    }

    return render(request, 'meals/meal_manager.html', context)


class AddMeal(LoginRequiredMixin, CreateView):
    model = Meal
    form_class = CreateMealForm
    template_name = 'meals/add_meal.html'
    success_url = reverse_lazy('meal_list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_form_kwargs(self):
        """ Passes the request object to the form class.
         This is necessary to only display members that belong to a given user"""

        kwargs = super(AddMeal, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


class UpdateMeal(LoginRequiredMixin, UpdateView):
    model = Meal
    form_class = CreateMealForm
    template_name = 'meals/update_meal.html'
    success_url = reverse_lazy('meal_list')

    def get_form_kwargs(self):
        kwargs = super(UpdateMeal, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

meals/templates/partials/addmeal.html
<form method="post" class="mealform">
    {% csrf_token %}
    {% load widget_tweaks %}

    <h5 class="mealform__date">[[activeDateFormatted]]</h5>
    <small class="mealform__helptext">Add a meal</small>

    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <label class="input-group-text">{{form.name.label}}</label>
        </div>
        {% render_field form.name class="form-control" %}
    </div>


    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <label class="input-group-text" for="id_mealtime">{{form.mealtime.label}}</label>
        </div>
        {% render_field form.mealtime v-model="mealTime" class="custom-select" %}
    </div>

    <div style="display:none;" class="input-group mb-3">
        <div class="input-group-prepend">
            <label class="input-group-text" for="id_mealtime">{{form.date.label}}</label>
        </div>
        {% render_field form.date v-model="activeDate" class="form-control" %}
    </div>

    <div class="checkbox-group">
        <h6>{{form.members.label_tag}}</h6>
        {% render_field form.members checked=true %}
    </div>

    <input type="submit" value="Add" class="btn btn-sm btn-primary">

</form>

meals/templates/partials/addmealform.html
<form method="post" class="mealform">
    {% csrf_token %}
    {% load widget_tweaks %}

    <small class="mealform__helptext">Add a meal for</small>
    <h5 class="mealform__date">[[activeDateFormatted]]</h5>

    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <label class="input-group-text">{{form.name.label}}</label>
        </div>
        {% render_field form.name class="form-control" %}
    </div>


    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <label class="input-group-text" for="id_mealtime">{{form.mealtime.label}}</label>
        </div>
        {% render_field form.mealtime v-model="mealTime" class="custom-select" %}
    </div>

    <div style="display:none;" class="input-group mb-3">
        <div class="input-group-prepend">
            <label class="input-group-text" for="id_mealtime">{{form.date.label}}</label>
        </div>
        {% render_field form.date v-model="activeDate" class="form-control" %}
    </div>

    <div class="checkbox-group">
        <h6>{{form.members.label_tag}}</h6>
        {% render_field form.members checked=true %}
    </div>

    <input type="hidden" name="page" id="page" v-model="page">
    <input type="hidden" name="activeIndex" id="activeIndex" v-model="activeCardIndex">

    <input type="submit" value="Add" class="btn btn-sm btn-primary">

</form>

meals/templates/partials/mealscard.html
{% load static %}

<article v-for="(day, i) in schedule" class="card" :class="{ 
    'card--active': activeCardIndex === i }" @click="setActiveIndex(day, i)" v-on:click="activeDate = day.dateForForm">
    <h5 class="card__date">[[day.date]]</h5>

    <section v-if="mealTime == 'Breakfast'">
        <h6 class="card__mealtime card__mealtime--breakfast">Breakfast</h6>
        <ul class="card__meals">
            <li class="card__meal card__meal--breakfast" v-for="breakfast in day.breakfasts">
                <span class="card__meal__name">[[breakfast.name]]</span>

                <ul class="card__meal--members">
                    <li v-for="member in breakfast.members">
                        [[member]]
                    </li>
                </ul>

                <a v-on:click="deleteMeal(breakfast.id)" class="card__meal__delete">
                    <img src="{% static 'icons/exit.svg' %}" alt="Delete Meal">
                </a>
            </li>
        </ul>
    </section>

    <section v-if="mealTime == 'Lunch'">
        <h6 class="card__mealtime card__mealtime--lunch">Lunch</h6>
        <ul class="card__meals">
            <li class="card__meal card__meal--lunch" v-for="lunch in day.lunches">
                <span class="card__meal__name">[[lunch.name]]</span>

                <ul class="card__meal--members">
                    <li v-for="member in lunch.members">
                        [[member]]
                    </li>
                </ul>

                <a v-on:click="deleteMeal(lunch.id)" class="card__meal__delete">
                    <img src="{% static 'icons/exit.svg' %}" alt="Delete Meal">
                </a>
            </li>
        </ul>
    </section>

    <section v-if="mealTime == 'Dinner'">
        <h6 class="card__mealtime card__mealtime--dinner">Dinner</h6>
        <ul class="card__meals">
            <li class="card__meal card__meal--dinner" v-for="dinner in day.dinners">
                <span class="card__meal__name">[[dinner.name]]</span>

                <ul class="card__meal--members">
                    <li v-for="member in dinner.members">
                        [[member]]
                    </li>
                </ul>

                <a v-on:click="deleteMeal(dinner.id)" class="card__meal__delete">
                    <img src="{% static 'icons/exit.svg' %}" alt="Delete Meal">
                </a>


            </li>
        </ul>

    </section>
    <a class="card__expand" v-bind:href="mealDetail(day.dateForForm)"><img src="{% static 'icons/expand.svg' %}"
            alt="view full details"></a>
    <div class="card__overlay"></div>
</article>

meals/templates/partials/mealtimecontrols.html
<div class="meallist__calendar__mealtimecontrols">
    <a v-on:click="mealTime = 'Breakfast'" v-bind:class="{'custom-btn--breakfast--active': mealTime == 'Breakfast'}"
        class="custom-btn custom-btn--breakfast">Breakfast</a>
    <a v-on:click="mealTime = 'Lunch'" v-bind:class="{'custom-btn--lunch--active': mealTime == 'Lunch'}"
        class="custom-btn custom-btn--lunch">Lunch</a>
    <a v-on:click="mealTime = 'Dinner'" v-bind:class="{'custom-btn--dinner--active': mealTime == 'Dinner'}"
        class="custom-btn custom-btn--dinner">Dinner</a>
</div>

meals/templates/partials/memberfilter.html
<section class="filtermembers">
    {% for member in members %}

    <label for="{{member.name}}" class="filtermembers__member">
        <input type="checkbox" v-model="checkedMembers" name="members" value="{{member.name}}" id="{{member.name}}"
            checked>
        <div class="filtermembers__member__photo">
            <img src="{{member.photo.url}}" />
        </div>
        {{member.name}}
    </label>

    {% endfor %}
</section>